name: 'PR Pulse'
description: 'Generate weekly reports of all code changes in a GitHub repository'
author: 'Ajinkya Indulkar'
branding:
  icon: 'activity'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub token for repository access'
    required: true
  repository:
    description: 'Target repository in format owner/repo'
    required: true
  days:
    description: 'Number of days to look back for PRs'
    required: false
    default: '7'
  output_format:
    description: 'Output format (table or json)'
    required: false
    default: 'table'
  verbose:
    description: 'Show detailed progress logs'
    required: false
    default: 'false'
  command:
    description: 'Command to run (list, detail, summary)'
    required: false
    default: 'summary'
  pr_number:
    description: 'Pull request number (required only for detail command)'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    INPUT_REPOSITORY: ${{ inputs.repository }}
    INPUT_DAYS: ${{ inputs.days }}
    INPUT_OUTPUT_FORMAT: ${{ inputs.output_format }}
    INPUT_VERBOSE: ${{ inputs.verbose }}
    INPUT_COMMAND: ${{ inputs.command }}
    INPUT_PR_NUMBER: ${{ inputs.pr_number }}
