name: "PR Pulse"
description: "GitHub Action to analyze merged GitHub pull requests and generate Pulse insights"
author: "Ajinkya Indulkar"
branding:
  icon: "activity"
  color: "blue"

inputs:
  github_token:
    description: "GitHub token for repository access"
    required: true
  api_key:
    description: "GEMINI API key to generate insights summary"
    required: true
  repository:
    description: "Target repository in format owner/repo"
    required: true
  days:
    description: "Number of days to look back for PRs"
    required: false
    default: "7"
  share:
    description: "Share insights on Slack"
    required: false
    default: "false"
  slack_webhook_url:
    description: "Slack webhook URL to share insights"
    required: false
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    GENAI_API_KEY: ${{ inputs.api_key }}
    INPUT_REPOSITORY: ${{ inputs.repository }}
    INPUT_DAYS: ${{ inputs.days }}
    INPUT_SHARE: ${{ inputs.share }}
    SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
