[project]
name = "uv-boilerplate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.7.0",
    "pygithub>=2.6.1",
    "slack-sdk>=3.35.0",
    "typer>=0.15.2",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ipython>=9.0.2",
    "pre-commit>=4.2.0",
]
