name: test-action

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "target repository in format owner/repo"
        required: true
        type: string
      days:
        description: "number of days to look back for PRs"
        required: false
        default: "7"
        type: string
      share:
        description: "share insights on Slack"
        required: false
        default: "false"
        type: boolean
      slack_webhook_url:
        description: "Slack webhook URL to share insights"
        required: false
        default: ""
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: generate insights summary
        uses: ajndkr/pr-pulse@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          api_key: ${{ secrets.GEMINI_API_KEY }}
          repository: ${{ github.event.inputs.repository }}
          days: ${{ github.event.inputs.days }}
          share: ${{ github.event.inputs.share }}
          slack_webhook_url: ${{ github.event.inputs.slack_webhook_url }}
